### ISSUE TITLE
Eval hack

### ISSUE THREAD

**Issue by kfatehi** [mixflame/Hokkaido#1]
Attempt to successfully port ansiterm as had been needed by motion-redgreen and a limitation with "eval" will be revealed. Support for eval will help support more gems and possibly make this tool have high success rate.

**Comment by mixflame** [comment]
Yes true. Only thing I noticed was that it can't do this job exactly because of having to execute the code and know what to define. Just a little tooo complicated. But we can detect the exact area and produce FIXME, which is still incredibly useful and better than searching for eval.. and easier

**Comment by kfatehi** [comment]
Or you could fgrep for "eval" ... don't bother supporting it unless you can automate solving it IMHO.

**Comment by mixflame** [comment]
in progress

**Comment by mixflame** [comment]
hack eval
comment
reprint eval def as define_method

**Comment by mixflame** [comment]
sorta done.. just FIXMEs... it could parse but thats too intense for right now.
