### ISSUE TITLE
Load Order

### ISSUE THREAD

**Issue by kfatehi** [mixflame/Hokkaido#5]
Below you will find that I have paused output right before Names gets called.
I did this because I crash at line 8 when Names is undefined.

02:46 kiin: http://cl.ly/1D2B1j3X2b2M080o3U1q

```
➜  lib git:(master) ✗ ruby cucumber.rb

From: ./cucumber/ast/feature.rb @ line 7 :

     1: # require 'cucumber/ast/names'
     2: 
     3: module Cucumber
     4:   module Ast
     5:     # Represents the root node of a parsed feature.
     6:     class Feature #:nodoc:
 =>  7:       binding.pry
     8:       include Names
     9:       
    10:       attr_accessor :language
    11:       attr_writer :features, :background
    12:       attr_reader :file, :feature_elements

[1] pry(Cucumber::Ast::Feature)> Motion::FILES
=> ["cucumber/platform.rb",
 "cucumber/parser.rb",
 "cucumber/ast.rb",
 "cucumber/ast/comment.rb",
 "cucumber/ast/features.rb",
 "cucumber/ast/feature.rb"]
[2] pry(Cucumber::Ast::Feature)> Names
NameError: uninitialized constant Cucumber::Ast::Feature::Names
from (pry):2
[3] pry(Cucumber::Ast::Feature)> 
```

Bug was found with the code found here: https://github.com/jsilverMDX/Hokkaido/issues/4

```
02:47 jsilver_: you pryed before include Names
02:47 kiin: yes
02:47 jsilver_: oh
02:47 kiin: it crashes cuz Names isnt defined
02:47 kiin: ./cucumber/ast/feature.rb:8: uninitialized constant Cucumber::Ast::Feature::Names (NameError)
02:47 kiin: so i stored the file load order in Motion::FILES
02:47 jsilver_: could be a bug in cukes
02:47 kiin: so that we can examine
02:47 kiin: what files have been required
02:47 kiin: # require 'cucumber/ast/names'
02:47 kiin: was supposed to be loaded
02:48 kiin: but it was not
02:48 jsilver_: it should be in the files listed
02:48 kiin: as evidenced by the fact that it is not included in Motion::FILES yet
02:48 jsilver_: hmmm
02:48 jsilver_: fail then
02:48 kiin: app.files << File.expand_path(File.dirname(__FILE__) + 'cucumber/ast/names.rb')
02:48 jsilver_: bug
02:48 kiin: comes right after
02:48 jsilver_: ah
02:48 kiin: app.files << File.expand_path(File.dirname(__FILE__) + 'cucumber/ast/feature.rb')
02:48 jsilver_: load order
02:48 jsilver_: yep
02:48 kiin: should have came before
02:48 jsilver_: ticket bug
02:48 kiin: should i make a ticket?
02:48 kiin: kk
02:48 jsilver_: yes
02:49 jsilver_: switching load orders is a small price to pay though compared to manually removing all the requires
02:49 jsilver_: lolz!
```

**Comment by kfatehi** [comment]
```
06:22 jsilver_: i can fix it
06:22 jsilver_: require at -1 instead of 0 in arrea
06:22 jsilver_: h/o
06:22 jsilver_: the current way in which manifest is built is wrong
06:22 jsilver_: the array gets built wrong
06:22 jsilver_: will need a way to sort it
06:22 jsilver_: before the tool is really proper
06:22 jsilver_: but i need to sleep
```

Should be easy to fix this now by using the self-testing version of Hokkaido (First mentioned here https://github.com/jsilverMDX/Hokkaido/issues/4)

Here is the pull request for self-testing version: https://github.com/jsilverMDX/Hokkaido/pull/6

**Comment by mixflame** [comment]
if issue is still valid i can comment

@required_libs can become a hash {:file => [lib1, lib2, lib3], :file2 => [lib4, lib5, lib6]]

should become like

require lib1
require lib2
require lib3
require file

require lib4
require lib5
require lib6
require file2

just notes and a fix idea

**Comment by kfatehi** [comment]
yes it's still valid (Open)

**Comment by mixflame** [comment]
math applied that tries to swap the rrequired files before the file in which they are required

uses hash and array.. real easy to see what's happening

still seems to be some issue with the app test

seem to be much closer to correct load order now on branch 5_load_order

if we can fix this we've got a killer app

**Comment by mixflame** [comment]
the real solution is... use an array and find every time, applying the magic to the order:

file_path_index = required_libs.index(file_path)
require_index = required_libs[file_path_index - 1]

and maybe uniq-ing at the end if it leaves it in the right order. double load should be okay.

props to zenspider for finding this -- the only probably solution to the load order problems

then we should have a tool which can convert any gems which dont do any much meta programming 100%
